version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    working_dir: /app
    command: ["npm", "start"]

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app
    command: ["python3", "app.py"]
